version: '3.7'

services:
 mongodb:
    networks:
      - bantads
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"

 auth-service:
    image: your-docker-username/auth-service:latest
    container_name: auth-service
    depends_on:
      - mongodb
    environment:
      - SPRING_DATASOURCE_URL=mongodb://admin:secret@mongodb:27017/auth-db


  postgres-conta-r:
    image: postgres
    container_name: postgres-conta-r
    environment:
      POSTGRES_PASSWORD: "postgress"
    ports:
      - "5432:5432"
    networks:
      - bantads

  postgres-conta-cud:
    image: postgres
    container_name: postgres-conta-cud
    environment:
      POSTGRES_PASSWORD: "postgress"
    ports:
      - "5433:5432"
    networks:
      - bantads
      
  rabbitmq:
    container_name: rabbitmq
    networks:
      - bantads
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
  
  micro-conta:
    container_name: micro-conta
    image: conta:0.0.1-SNAPSHOT
    networks:
      - bantads
    depends_on:
      - rabbitmq
      - postgres-conta-cud
      - postgres-conta-r
    ports:
      - "5005:8080"
  
  micro-auth:
    container_name: micro-auth
    image: auth:0.0.1-SNAPSHOT
    networks:
      - bantads
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - "5005:8080"

networks:
  bantads:
    driver: bridge