version: '3'

services:
  mongodb:
    networks:
      - bantads
    container_name: mongodb
    image: mongo
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - "27017:27017"

  rabbitmq:
    container_name: rabbitmq
    networks:
      - bantads
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres-conta-r:
    image: postgres
    container_name: postgres-conta-r
    environment:
      POSTGRES_PASSWORD: "postgress"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - bantads

  postgres-conta-cud:
    image: postgres
    container_name: postgres-conta-cud
    environment:
      POSTGRES_PASSWORD: "postgress"
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - bantads
  
  postgres-cliente:
    image: postgres
    container_name: postgres-cliente
    environment:
      POSTGRES_PASSWORD: "postgress"
    ports:
      - "5434:5432"
    volumes:
      - ./init_cliente.sql:/docker-entrypoint-initdb.d/init_cliente.sql
    networks:
      - bantads

  postgres-gerente:
    image: postgres
    container_name: postgres-gerente
    environment:
      POSTGRES_PASSWORD: "postgress"
    ports:
      - "5435:5432"
    volumes:
      - ./init_gerente.sql:/docker-entrypoint-initdb.d/init_gerente.sql
    networks:
      - bantads
  
  micro-gerente:
    container_name: micro-gerente
    image: gerente:0.0.1-SNAPSHOT
    networks:
      - bantads
    depends_on:
      - postgres-gerente
    ports:
      - "5008:8080"

  micro-cliente:
    container_name: micro-cliente
    image: cliente:0.0.1-SNAPSHOT
    networks:
      - bantads
    depends_on:
      - postgres-cliente
    ports:
      - "5009:8080"
  
  micro-conta:
    container_name: micro-conta
    image: conta:0.0.1-SNAPSHOT
    networks:
      - bantads
    depends_on:
      - rabbitmq
      - postgres-conta-cud
      - postgres-conta-r
    ports:
      - "5005:8080"
  
  micro-auth:
    container_name: micro-auth
    image: auth:0.0.1-SNAPSHOT
    networks:
      - bantads
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - "5000:8080"

networks:
  bantads:
    driver: bridge